#!/bin/bash

gnuplot <<'EOF'

set style line 11 lc rgb '#808080' lt 1
set border 3 back ls 11
set tics nomirror out scale 0.75
set arrow from graph 1,0 to graph 1.05,0 size screen 0.025,15,60 filled ls 11
set arrow from graph 0,1 to graph 0,1.05 size screen 0.025,15,60 filled ls 11

set style line 12 lc rgb'#808080' lt 0 lw 1
set grid back ls 12
set datafile separator "|"
set key left top

#set lmargin at screen 0.2
set bmargin at screen 0.2
set rmargin at screen 0.95
set tmargin at screen 0.95

set style line 1 lc rgb '#0080f0' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 2 lc rgb '#d02020' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 3 lc rgb '#f08000' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 4 lc rgb '#20d020' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 5 lc rgb '#c0c0c0' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 6 lc rgb '#a020ff' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 7 lc rgb '#ff20a0' lt 3 pt 7 ps 1 lw 2 dt "- "
set style line 8 lc rgb '#000000' lt 3 pt 7 ps 1 lw 2 dt "- "

set style line 10 lc rgb '#0080f0' lt 1 pt 7 ps 2 lw 0
set style line 20 lc rgb '#d02020' lt 1 pt 7 ps 2 lw 0
set style line 30 lc rgb '#f08000' lt 1 pt 7 ps 2 lw 0
set style line 40 lc rgb '#20d020' lt 1 pt 7 ps 2 lw 0
set style line 50 lc rgb '#c0c0c0' lt 1 pt 7 ps 2 lw 0
set style line 60 lc rgb '#a020ff' lt 1 pt 7 ps 2 lw 0
set style line 70 lc rgb '#ff20a0' lt 1 pt 7 ps 2 lw 0
set style line 80 lc rgb '#000000' lt 1 pt 7 ps 2 lw 0

set title ''

set output "plot1.tex"
#set terminal pdf color enhanced size 3in,2in
set terminal epslatex size 3.4in,1.8in

#set format y "\$%.0F\$"
#set format y "%.0s\\\\\\\\cdot10^{%T}"
#set format y "%.0s . 10^{%T}"
#set format x "\$10^{%T}\$"
#set format y "\$10^{%T}\$"

#set ytics add ("" 0)
#set ytics 500000

#set xtics 500
#set mytics 10
#set mxtics 10

#set logscale x 
#set logscale y
#set yrange [1 to 1000];

#set xrange [100 to 1000000];
#set yrange [10 to 10000]

#set mytics 5
#set xtics add ("" 2000000)
#set ytics 10
#set xtics 50
#set mytics 2
#set key left top


#1/0 w p t "Run Time" ls 10, \
#1/0 w p t "\$2 \\\\log(n)\$" ls 20, \
#2*log(x)/log(2) with lines ls 2 t "" , \



set datafile separator ";" 

#set format x "\$%.0F\$"
set xrange [1 to 5]
#set format y "\$%.1F\$"
#set yrange [0 to 0.2]
set xtics 1
#set ytics 1

set xlabel 'capacity $c$'
set ylabel 'normalized pool size' offset 1,0

set key right top

plot \
1/0 w p t "\\small $\\lambda=3/4$" ls 10,\
1/0 w p t "\\small $\\lambda=1023/1024$" ls 20,\
"plot1.csv" using ($2) w p ls 1 t "", \
"plot1.csv" using ($3) w l ls 1 t "", \
"plot1.csv" using ($5) w p ls 2 t "", \
"plot1.csv" using ($6) w l ls 2 t "";
#1/0 w p t "$\\frac{4\\ln(4)}{c}+6c$" ls 30,\
#1/0 w p t "$4\\frac{\\ln(1024)}{c}+6c$" ls 60,\
#"plot1.csv" using ($4) w lp ls 3 t "", \
#"plot1.csv" using ($7) w lp ls 6 t "" ;
#1/0 w p t "\\small $\\ln(4)/c+1$" ls 10,\
#1/0 w p t "\\small $\\frac{\\ln(1024)}{c}+1$" ls 40,\

EOF

